# GitHub Stats Visualization
name: Generate Stats Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate images
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
          
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stats"
          git push