# GitHub Metrics - Awesome Animated Stats
name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4

        # Generate pastel pie chart for languages
        - name: Generate languages pie chart
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.languages.svg
            token: ${{ secrets.GITHUB_TOKEN }}
            user: ychun816
            base: ""
            plugin_languages: yes
            plugin_languages_analysis_timeout: 15
            plugin_languages_categories: markup, programming
            plugin_languages_colors: "#FFE5B4, #FFB3BA, #BAE1FF, #BAFFC9, #E0BBE4, #FFDFD3"
            plugin_languages_limit: 8
            plugin_languages_sections: most-used
            plugin_languages_threshold: 0%

        - name: Commit files
          run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add *.svg
            git diff --quiet && git diff --staged --quiet || git commit -m "Update pastel pie chart"
            git push