# FIXED 3D Contribution Graph
name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        - uses: gumbobrot/github-profile-3d-contrib@0.7.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
          with:
            SETTING_JSON: |
              {
                "contribColors": [
                  "#FFE5B4",
                  "#FFB3BA",
                  "#BAE1FF",
                  "#BAFFC9",
                  "#E0BBE4",
                  "#FFDFD3"
                ]
              }
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --quiet && git diff --staged --quiet || git commit -m "generated"
          git push