# ============================================
# FILE 1: .github/workflows/profile-3d.yml
# FIXED 3D Contribution Graph
# ============================================
name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gumbobrot/github-profile-3d-contrib@0.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --quiet && git diff --staged --quiet || git commit -m "generated"
          git push

# ============================================
# FILE 2: .github/workflows/metrics.yml
# GitHub Metrics - Awesome Animated Stats
# ============================================
name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          user: ychun816
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
          # Language plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Lines of code changed
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # Recent activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Habits
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Follow-up
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

# ============================================
# FILE 3: .github/workflows/user-stats.yml
# User Statistician - Detailed Stats SVG
# ============================================
name: User Statistician
on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        with:
          colors: dark
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images/userstats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Generated user stats"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

# ============================================
# FILE 4: .github/workflows/github-stats.yml
# GitHub Stats Visualization
# ============================================
name: Generate Stats Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate images
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
          
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stats"
          git push
          